name: build
on: [push, pull_request]
jobs:
  test:
    strategy:
      matrix:
        go-version: ["1.19","1.20","1.21"]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Set up Golang ${{ matrix.go-version }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}
        id: go

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.52

      - name: Test
        env:
          TZ: Asia/Shanghai
        run: |
          make test
          bash <(curl -s https://codecov.io/bash) -t ${{ secrets.CODECOV_TOKEN}}
